<?php
// +----------------------------------------------------------------------
// | RXThinkCMF_EVL8_PRO前后端分离旗舰版框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2021 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | 作者: 牧羊人 <rxthinkcmf@163.com>
// +----------------------------------------------------------------------
// | 免责声明:
// | 本软件框架禁止任何单位和个人用于任何违法、侵害他人合法利益等恶意的行为，禁止用于任何违
// | 反我国法律法规的一切平台研发，任何单位和个人使用本软件框架用于产品研发而产生的任何意外
// | 、疏忽、合约毁坏、诽谤、版权或知识产权侵犯及其造成的损失 (包括但不限于直接、间接、附带
// | 或衍生的损失等)，本团队不承担任何法律责任。本软件框架只能用于公司和个人内部的法律所允
// | 许的合法合规的软件产品研发，详细声明内容请阅读《框架免责声明》附件；
// +----------------------------------------------------------------------

namespace App\Services;


use App\Models\ArticleModel;

/**
 * 文章管理-服务类
 * @author 牧羊人
 * @since 2021/6/9
 * Class ArticleService
 * @package App\Services
 */
class ArticleService extends BaseService
{
    /**
     * 构造函数
     * @author 牧羊人
     * @since 2021/6/9
     * ArticleService constructor.
     */
    public function __construct()
    {
        $this->model = new ArticleModel();
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2021/6/9
     * @author 牧羊人
     */
    public function edit()
    {
        $data = request()->all();
        // 封面处理
        $cover = getter($data, "cover");
        if (!empty($cover)) {
            if (strpos($cover, "temp") !== false) {
                $data['cover'] = save_image($cover, 'article');
            } else {
                $data['cover'] = str_replace(IMG_URL, "", $cover);
            }
        }
        // 文章图集
        $imgsList = isset($data['imgs']) ? $data['imgs'] : [];
        if ($imgsList) {
            $imgStr = [];
            foreach ($imgsList as $key => $val) {
                if (strpos($val, "temp")) {
                    //新上传图片
                    $imgStr[] = save_image($val, 'article');
                } else {
                    //过滤已上传图片
                    $imgStr[] = str_replace(IMG_URL, "", $val);
                }
            }
            $data['imgs'] = serialize($imgStr);
        }

        //内容处理
        save_image_content($data['content'], $data['title'], "article");
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

    public function status()
    {
        // 参数
        $data = request()->all();
        // 文章ID
        $id = isset($data['id']) ? intval($data['id']) : 0;
        if (empty($id)) {
            return message("文章ID不能为空", false);
        }
        // 文章状态
        $status = isset($data['status']) ? $data['status'] : 0;
        if (empty($status)) {
            return message("文章状态不能为空", false);
        }
        $result = $this->model
            ->where("id", $id)
            ->update([
                'status' => $status,
            ]);
        if (!$result) {
            return message("设置状态失败", false);
        }
        // 删除缓存
        $this->model->cacheDelete($id);
        return message();
    }

}
