<?php
// +----------------------------------------------------------------------
// | RXThinkCMF_EVL8_PRO前后端分离旗舰版框架 [ RXThinkCMF ]
// +----------------------------------------------------------------------
// | 版权所有 2021 南京RXThinkCMF研发中心
// +----------------------------------------------------------------------
// | 官方网站: http://www.rxthink.cn
// +----------------------------------------------------------------------
// | 作者: 牧羊人 <rxthinkcmf@163.com>
// +----------------------------------------------------------------------
// | 免责声明:
// | 本软件框架禁止任何单位和个人用于任何违法、侵害他人合法利益等恶意的行为，禁止用于任何违
// | 反我国法律法规的一切平台研发，任何单位和个人使用本软件框架用于产品研发而产生的任何意外
// | 、疏忽、合约毁坏、诽谤、版权或知识产权侵犯及其造成的损失 (包括但不限于直接、间接、附带
// | 或衍生的损失等)，本团队不承担任何法律责任。本软件框架只能用于公司和个人内部的法律所允
// | 许的合法合规的软件产品研发，详细声明内容请阅读《框架免责声明》附件；
// +----------------------------------------------------------------------

namespace App\Models;

use Illuminate\Support\Facades\DB;


/**
 * 文章-模型
 * @author 牧羊人
 * @since 2021/6/9
 * Class ArticleModel
 * @package App\Models
 */
class ArticleModel extends BaseModel
{
    // 设置数据表
    protected $table = "article";

    /**
     * 获取记录信息
     * @param int $id 记录ID
     * @return array|string
     * @author 牧羊人
     * @since 2021/6/9
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 文章封面
            if ($info['cover']) {
                $info['cover'] = get_image_url($info['cover']);
            }

            // 获取栏目
            if ($info['cate_id']) {
                $itemCateModel = new ItemCateModel();
                $cateName = $itemCateModel->getCateName($info['cate_id'], ">>");

                // 获取站点信息
                $itemModel = new ItemModel();
                $itemInfo = $itemModel->getInfo($info['item_id']);

                // 拼接字符
                $info['cate_name'] = $itemInfo['name'] . ">>" . $cateName;
            }
            // 获取分表
            $tableName = $this->getArticleTable($id);
            $articleModel = DB::table($tableName);
            $articleInfo = $articleModel->find($id);
            if ($articleInfo) {
                $articleInfo = json_decode(json_encode($articleInfo), true);
                if (isset($articleInfo['content']) && $articleInfo['content']) {
                    while (strstr($articleInfo['content'], "[IMG_URL]")) {
                        $articleInfo['content'] = str_replace("[IMG_URL]", IMG_URL, $articleInfo['content']);
                    }
                }
                $info = array_merge($info, $articleInfo);
            }

            // 文章图集
            if (isset($info['imgs'])) {
                $imgsList = unserialize($info['imgs']);
                foreach ($imgsList as &$val) {
                    $val = get_image_url($val);
                }
                $info['imgs'] = $imgsList;
            }
        }
        return $info;
    }

    /**
     * 添加或编辑
     * @param array $data 数据源
     * @param string $error 错误信息
     * @param bool $isSql 打印SQL
     * @return bool|int|string
     * @throws \think\db\exception\BindParamException
     * @since 2020/7/4
     * @author 牧羊人
     */
    public function edit($data = [], &$error = '', $isSql = false)
    {
        // 获取数据表字段
        $column = $this->getFieldsList($this->table);
        $item = [];
        foreach ($data as $key => $val) {
            if (!in_array($key, array_keys($column))) {
                $item[$key] = $val;
                unset($data[$key]);
            }
        }

        // 开启事务
//        $this->startTrans();
        $rowId = parent::edit($data, $error, $isSql);
        if (!$rowId) {
            //事务回滚
//            $this->rollback();
            return false;
        }
        $result = $this->saveArticleInfo($rowId, $item);
        if (!$result) {
            // 事务回滚
//            $this->rollback();
            return false;
        }
        // 提交事务
//        $this->commit();
        return $rowId;
    }

    /**
     * 保存文章附表信息
     * @param $id 记录ID
     * @param $item 附表数据
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     * @author 牧羊人
     * @since 2020/7/4
     */
    public function saveArticleInfo($id, $item)
    {
        $tableName = $this->getArticleTable($id);
        $info = DB::table($tableName)->find($id);
        $info = json_decode(json_encode($info), true);

        $data = [];
        if (!$info) {
            $data['id'] = $id;
        }
        $data['content'] = $item['content'];
        if ($item['guide']) {
            $data['guide'] = $item['guide'];
        }
        if (isset($item['imgs'])) {
            $data['imgs'] = $item['imgs'];
        }

        //获取分表模型
        $tableName = $this->getArticleTable($id);
        $articleModel = DB::table($tableName);
        if ($info['id']) {
            $result = $articleModel->where('id', $id)->update($data);
        } else {
            $result = $articleModel->insert($data);
        }
        if ($result !== false) {
            return true;
        }
        return false;
    }

    /**
     * 获取文章附表名
     * @param $id 记录ID
     * @param bool $isPrefix 是否包含表前缀
     * @return string
     * @since 2020/7/4
     * @author 牧羊人
     */
    public function getArticleTable($id, $isPrefix = false)
    {
        $tableName = substr($id, -1, 1);
        $tableName = "article_{$tableName}";
        if ($isPrefix) {
            $tableName = DB_PREFIX . $tableName;
        }
        return $tableName;
    }

}
